---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp-cm
  labels:
    app: northwind
data:
  DB_USER: root
  DB_HOST: nwdb-mysql-master.nwapp.svc.cluster.local
  DB_PASSWORD: changeit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  labels:
    app: northwind

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nwapp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nwapp-pod
      labels:
        dept: engineering
        app: nwapp-pod
    spec:
      containers:
      - name: nw-container
        image: stackupiss/northwind-app:v2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: nwapp-cm
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nwapp-cm
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: nwdb-cluster-secret
                key: ROOT_PASSWORD
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
              fieldRef:
                fieldPath: status.podIP
        livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /health
              port: nwapp-port
        ports:
          - name: nwapp-port
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nwapp-svc
  labels:
    app: northwind
spec:
  type: ClusterIP
  # type: LoadBalancer
  selector:
    app: nwapp-pod
  ports:
    - name: app-port
      port: 8080 # external facing
      targetPort: nwapp-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nwapp-ing
  labels:
    app: northwind
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rpm: "15"
spec:
  rules: 
  - host: "nwapp.188.166.206.11.nip.io"
    http:
      paths: 
      - path: /
        backend:
          serviceName: nwapp-svc
          servicePort: app-port
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nwapp-hpa
  labels:
    app: northwind
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nwapp-deploy
  targetCPUUtilizationPercentage: 20
  minReplicas: 2
  maxReplicas: 5
