---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  labels:
    dept: engineering
    app: fortune

spec:
  replicas: 3
  selector:
    matchLabels:
      dept: engineering
      app: fortune-pod
  template:
    metadata:
      name: fortune-pod
      labels:
        dept: engineering
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: chukmunnlee/fortune:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PORT
          value: "8080"
        ports:
          - name: fortune-port
            containerPort: 8080
