---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp2-cm
  labels:
    app: northwind
data:
  DB_USER: root
  DB_HOST: nwdb-svc.nwapp.svc.cluster.local
  DB_PASSWORD: changeit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp2-deploy
  labels:
    app: northwind

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nwapp2-pod
  template:
    metadata:
      name: nwapp2-pod
      labels:
        dept: engineering
        app: nwapp2-pod
    spec:
      containers:
      - name: nwapp2-container
        image: stackupiss/northwind-app:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: nwapp2-cm
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nwapp2-cm
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: nwdb-secret
                key: MYSQL_ROOT_PASSWORD
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
              fieldRef:
                fieldPath: status.podIP
        livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /health
              port: nwapp2-port
        ports:
          - name: nwapp2-port
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nwapp2-svc
  labels:
    app: northwind
spec:
  type: ClusterIP
  # type: LoadBalancer
  selector:
    app: nwapp2-pod
  ports:
    - name: app-port
      port: 8080 # external facing
      targetPort: nwapp2-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nwapp-ing
  labels:
    app: northwind
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # generally used for api and not websites due to the resources not being remapped, will default back to default backend if nothing to replace
spec:
  rules: 
  - host: "nwapp.167.172.6.184.nip.io"
    http:
      paths: 
      - path: /v1(/|$)(.*)
        backend:
          serviceName: nwapp-svc
          servicePort: app-port      
      - path: /v2(/|$)(.*)
        backend:
          serviceName: nwapp2-svc
          servicePort: app-port
