---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  labels:
    dept: engineering
    app: fortune

spec:
  replicas: 2
  selector:
    matchLabels:
      dept: engineering
      app: fortune-pod
  template:
    metadata:
      name: fortune-pod
      labels:
        dept: engineering
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: chukmunnlee/fortune:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PORT
          value: "8080"
        ports:
          - name: fortune-port
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
  labels:
    app: fortune
spec:
  type: ClusterIP
  selector:
    app: fortune-pod
  ports:
  - port: 8080
    targetPort: fortune-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fortune-ing
  labels:
    app: fortune
spec:
  rules:
  - host: "fortune.167.172.6.184.nip.io"
    http:
      paths:
      - path: /
        backend: 
          serviceName: fortune-svc
          servicePort: fortune-port
