# kubectl apply -f fortune-k8-deployment.yml --record
# kubectl scale deploy/fortune-deploy -n myns --replicas=3
# kubectl rollout history deploy/fortune-deploy -n myns
# 

---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels: 
    dept: engineering
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: myns
  labels:
    dept: engineering
    app: fortune

spec:
  replicas: 2
  selector:
    matchLabels:
      dept: engineering
      app: fortune-pod
  template:
    metadata:
      name: fortune-pod
      namespace: myns
      labels:
        dept: engineering
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: chukmunnlee/fortune:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PORT
          value: "8080"
        ports:
          - name: fortune-port
            containerPort: 8080
