# kubectl create ns nwapp
# kubectl apply -f nwdb-k8-secret.yml -n nwapp --record
# kubectl get secret -n nwapp
# kubectl get secret/nwdb-secret -n nwapp -o yaml
# kubectl delete secret/mydb-secret -n nwapp
# kubectl create secret generic nwdb-secret --from-literal MYSQL_ROOT_PASSWORD=changeit
# kubectl get secret/nwdb-secret -o yaml
# kubectl apply -f nwdb-k8-secret.yml -n nwapp --record
# kubectl rollout history deploy/nwdb-deploy -n nwapp

---
apiVersion: v1
kind: Secret
metadata:
  name: nwdb-secret
  labels: 
    app: northwind

data:
  MYSQL_ROOT_PASSWORD: 'Y2hhbmdlaXQ='
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb-deploy
  labels:
    app: northwind

spec:
  replicas: 1
  selector:
    matchLabels:
      dept: engineering
      app: nw-pod
  template:
    metadata:
      name: nw-pod
      labels:
        dept: engineering
        app: nw-pod
    spec:
      containers:
      - name: nw-container
        image: chukmunnlee/nwdb:v3
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: nwdb-secret
                key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "northwind"
        livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            exec:
              command:
                - bash
                - -c
                - "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD} || exit 1"
        ports:
          - name: nwdb-port
            containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: nwdb-svc
  labels:
    app: northwind
spec:
  type: ClusterIP
  selector:
    app: nw-pod
  ports:
    - name: db-port
      port: 3306 # external facing
      targetPort: nwdb-port
